### PR TITLE
upload OS midterm review notes

### PR DESCRIPTION
**Pull request by RuixiangJiang**

### CODE REVIEW

**Comment by NYH-Dolphin** [comment]
Hey Ruixiang, thanks for your contribution!

Please put the file under the `Note` folder

**Comment by RuixiangJiang** [comment]
> Hey Ruixiang, thanks for your contribution!
> 
> Please put the file under the `Note` folder

I've moved it ^_^

**Comment by RuixiangJiang** [comment]
by the way, it's also a good idea to use VSCode to connect to GitHub without downloading anything to one's PC

**Comment by NYH-Dolphin** [comment]
> by the way, it's also a good idea to use VSCode to connect to GitHub without downloading anything to one's PC

Thank you for your advice. Can you provide a tutorial for using VSCode to connect to this repository? I can put it in README.

**Pull request merged**
